### ISSUE TITLE
Double jump bug

### ISSUE THREAD

**Issue by apaatsio** [excaliburjs/sample-platformer#91]
It's possible to perform a "double jump". It seems that sometimes when you press the Up key right at the peak of the first jump, it performs a second jump. I'm sure this is not the desired behavior. This happens maybe about 1 out of 20 times when I try to deliberately do it.

![double_jump](https://user-images.githubusercontent.com/195210/92152983-da2efd00-ee23-11ea-99a3-1f879f6bd509.gif)

Excalibur: 0.24.4
sample-platformer: 717c7a1f

**Comment by eonarheim** [comment]
@apaatsio Good find! Double jumps definitely not intentional. 

Must be something odd about https://github.com/excaliburjs/sample-platformer/blob/master/src/bot.ts#L59 allow the jump to be registered https://github.com/excaliburjs/sample-platformer/blob/master/src/bot.ts#L99

**Comment by eonarheim** [comment]
Okay, this is a subtle issue but I believe this is because the collision resolution runs after actor update.

Immediately after the jump because the update is complete the jump impulse won't be applied until the next frame.
![image](https://user-images.githubusercontent.com/612071/92188767-0f871b00-ee23-11ea-800c-4026292125dd.png)

In the same frame, collision is processed and the actor geometry is still intersecting so onGround is set back to true, making a double jump possible in the very next frame.
![image](https://user-images.githubusercontent.com/612071/92188856-5543e380-ee23-11ea-8879-a230459a5283.png)

Potential solutions:
* Switch to `onPreUpdate` to ensure impulse is processed the same frame as collisions
* Shift the actor `pos.y` up to keep from re-colliding with the floor the same frame as the jump

**Comment by eonarheim** [comment]
@apaatsio I switched to `onPreUpdate` seems to do the right thing, thanks for the find!
